version: "3.7"
services:
  app:
    build:
      args:
        user: roginho
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php_7.4
    container_name: autonomus-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - network

  db:
    image: mysql:8.0
    container_name: autonomus-db
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: autonomus-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - network

networks:
  network:
    driver: bridge